creation_rules:
  - path_regex: common(\.enc)?\.env$
    age: "age1ynlzj96eh63u8rwq4k77pa5s5kwjjxu5g8lwcn0vnzhkw2ny456qj3lvsd"
  - path_regex: apps/.*/secrets(\.enc)?\.env$
    age: "age1ynlzj96eh63u8rwq4k77pa5s5kwjjxu5g8lwcn0vnzhkw2ny456qj3lvsd"
    # Generate on server: age-keygen -o .age-key.txt
    # Public key is printed by age-keygen, or retrieve with: age-keygen -y .age-key.txt
