services:

  valkey:
    image: valkey/valkey:9.1.0
    container_name: traefik-valkey
    command: valkey-server --save 60 1 --loglevel warning
    networks:
      - traefik-public
      - traefik-internal
    volumes:
      - ${DATA_DIR}/traefik/valkey:/data
    restart: unless-stopped

  traefik:
    image: traefik:v3.7.4
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yaml
    environment:
      - DOMAIN=${DOMAIN}
      - DISKSTATION_DOMAIN=${DISKSTATION_DOMAIN}
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${TRAEFIK_ACME_EMAIL}
    depends_on:
      - valkey
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_DIR}/traefik/letsencrypt:/letsencrypt
      - ${DATA_DIR}/traefik/auth:/etc/traefik/auth:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/dynamic:/etc/traefik/dynamic:ro
    networks:
      - traefik-public
      - traefik-internal
    restart: unless-stopped

networks:
  traefik-public:
    name: traefik-public
  traefik-internal:
    name: traefik-internal
